// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/mdapathy/architecture-2/server/forums"
	"github.com/mdapathy/architecture-2/server/users"
)

// Injectors from modules.go:

func ComposeApiServer(port HttpPortNumber) (*ChatApiServer, error) {
	db, err := NewDbConnection()
	if err != nil {
		return nil, err
	}
	storage := forums.NewStore(db)
	httpHandlerFunc := forums.HttpHandler(storage)
	usersStorage := users.NewStore(db)
	usersHttpHandlerFunc := users.HttpHandler(usersStorage, storage)
	chatApiServer := &ChatApiServer{
		Port:          port,
		ForumsHandler: httpHandlerFunc,
		UsersHandler:  usersHttpHandlerFunc,
	}
	return chatApiServer, nil
}
